### ISSUE TITLE
onClose && onOffline ?

### ISSUE THREAD

**Issue by Fr33maan** [jamesjara/aws-iot-device-sdk-js-react-native#1]
Hello, 

I'm making a RN app and I would like to use a serverless infrastructure so I naturaly found your module. 
I see in [index.js](https://github.com/jamesjara/react-native-aws-iot-device-shadows/blob/master/index.js#L68) that we have callbacks for those events but I don't see them in the doc.
Is there any particular reason for not encouraging users to use them ? 
I'm not familiar at all with IoT and MQTT protocol.

**Comment by jamesjara** [comment]
Not really, I'm just overloaded with work, feel free to use those methods and add it to the doc if you can
